### ISSUE TITLE
Unable to locate and issues on both installing methods.

### ISSUE THREAD

**Issue by EasyCompZLD** [dr41nU/csv-importer_ynh#1]
![Schermafbeelding 2020-12-12 om 08 11 26](https://user-images.githubusercontent.com/67462665/101977956-a862d900-3c51-11eb-8f24-592f5181e939.png)
No manifest.json.. 

![Schermafbeelding 2020-12-12 om 08 12 10](https://user-images.githubusercontent.com/67462665/101977982-dd6f2b80-3c51-11eb-8260-d89364d7d1a2.png)
Unable to, you can read that part and underneath it says could not fetch or acquire the pack. but they are there...

**Comment by EasyCompZLD** [comment]
https://github.com/dr41nU/csv-importer_ynh FIX YOUR READMES URL PLZX

**Comment by EasyCompZLD** [comment]
Please rather  fix the whole thing 

The user firefly-iii-csv-importer was not found
Removing the dedicated system user... [00h00m,00s]
Removing logrotate configuration... [00h00m,01s]
[Error] Do not use ynh_remove_php to remove php7.3 !
Removing dependencies... [00h00m,01s]
'/etc/php/7.3/fpm/pool.d/firefly-iii-csv-importer.conf' wasn't deleted because it doesn't exist.
Removing php-fpm configuration... [00h00m,01s]
'/etc/nginx/conf.d/easycomp.cloud.d/firefly-iii-csv-importer.conf' wasn't deleted because it doesn't exist.
Removing nginx web server configuration... [00h00m,00s]
Removing app main directory... [00h00m,03s]
ynh_secure_remove called with empty argument, ignoring.
E: Unable to locate package firefly-iii-csv-importer-ynh-deps
Removing dependencies... [00h00m,02s]
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
Removing the MySQL database... [00h00m,01s]
Loading installation settings... [00h00m,00s]
Removing the app following the installation failure...
Could not complete the operation 'Install the 'firefly-iii-csv-importer' app'. Please provide the full log of this operation by clicking here to get help
Could not install firefly-iii-csv-importer: An error occurred inside the app installation script
Do not use ynh_install_php to install php7.3
Installing dependencies... [00h00m,01s]
Storing installation settings... [00h00m,03s]
Validating installation parameters... [00h00m,00s]
Installing firefly-iii-csv-importer...

**Comment by dr41nU** [comment]
Hello EasyCompZLD,
This package was experimental and should not be used. As you say, the entire code is broken. Moreover the package had not been upgraded whereas the lead package (ie https://github.com/YunoHost-Apps/firefly-iii) is now several versions behind.
Best regards,
Laurent

**Comment by EasyCompZLD** [comment]
But why is it abandoned ? :’( I like the thing so much tough I need to have it!  But the creator of the importer is just a nasty bitch I asked him kindly why he did not even create an simpeler way for these plugins to install i.e. like yuno does or Wordpress. But then he go all like na go figurer I dont care. 
Als o then why the documentation on his end was so vague. I guess that he never wanted to share any of it.

Take look: to all these forwarded parts and his selfish ego response I think that he lost his human feeling and became an android. 


Op 12 dec. 2020, om 07:46 heeft S.A.C. Abdel Nasser | EasyComp Zeeland <shaady@easycompzeeland.nl <mailto:shaady@easycompzeeland.nl>> het volgende geschreven:

Are you having a morning mood mister? 

Don’t tell me anything about realisation,  but use your brain man why should you keep us let us invent our own wheels? You either share something open sourced so thus with documentation or you don’t and you get a patent. 
Has also nothing to do with silly and don’t judge me man. I cant help it dat hi did my master at Oxford but that still doesn’t mean that I should know anything right away. But if nearly every web app these day have an built in option to import and export content right? Then why did you cripple it on purpose and fuck our time because you are to childish in the fact that “ I had to figure it all my self so you shout do that tooooo” your sounding just a bit like a kid of 5 maybe 6 to me. 

So you don’t care about what your software is capable of or you don’t care about the users in general, my friend let me explain to you your own plugin was  designed to make things easily manageable right? So we tent do install all systems, servers and what not unattended. Because it saves so many time! Not that we could get it working of course but why the f should I do something that you did already? 

And if you really don’t care? Then stop this man find another Job do something you like actually if you don’t want to share anything you developed, wel don’t because now it looks like that your either an ego person or you we’re forced to share it, don’t get me wrong there but can you look from  a distance to this? And then answer me on; Why would’t you even make it so that it just becomes an option or thing to install plugins right away, sure we shall go the reinvention way now but al I ask Is a little humanity. If we’re the last 2 man on earth and I found something to eat I most defiantly shared it, but do I get a peace of food back if you did you probably would tell me that you had this great loof of bread but where is it then? 


 <https://easycompzeeland.nl/>	
S.A.C. Abdel Nasser | Algemeen Directeur
T: +31 (0)85 785 10 11 <tel:+31(0)857851011> <tel:>
E: Shaady@EasyCompZeeland.nl <mailto:Shaady@EasyCompZeeland.nl> | W: https://EasyCompZeeland.nl <https://easycompzeeland.nl/>
 <https://www.facebook.com/easycompzeeland>	 <https://www.twitter.com/easycompzld>
De inhoud van dit bericht is alleen bestemd voor de geadresseerde en kan vertrouwelijke of persoonlijke informatie bevatten. Als u dit bericht onbedoeld heeft ontvangen verzoeken wij u het te vernietigen en de klantenservice, of de medewerker van EasyComp Zeeland direct te informeren. Het is niet toegestaan om een bericht dat niet voor u bestemd is te vermenigvuldigen dan wel te verspreiden. Aan dit bericht inclusief de bijlagen kunnen geen rechten ontleend worden, tenzij schriftelijk anders wordt overeengekomen. EasyComp Zeeland, aanvaardt geen enkele aansprakelijkheid voor schade en/of kosten die voortvloeien uit onvolledige en/of foutieve informatie in e-mailberichten.

> Op 12 dec. 2020, om 07:22 heeft James Cole <james@firefly-iii.org <mailto:james@firefly-iii.org>> het volgende geschreven:
> 
> Yeah no. You have to realize I like to write code. I don't like writing installers or one-click upload unzip shit that can handle the billion things that can go wrong when users upload this to random servers. I'm not interested. There are Docker images and configurations that are pretty much ready-made but you got to know what you're doing.
> 
> The instructions are vague because the moment you start explaining every silly little you have to keep going. Before you know it the tutorial is 40 pages and that's not user-friendly either.
> 
> Feel free to build it if you're interested. You have to realise I don't really care. Plenty of people manage just fine. There's nothing in it for me to make it more user friendly or noob-ready. I do this for free in my spare time. Even if my salary doubles I still get nothing.
> 
> Cheers,
> James
> 
> 
> ‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
> On Saturday, December 12th, 2020 at 6:05 AM, S.A.C. Abdel Nasser | EasyComp Zeeland <shaady@easycompzeeland.nl <mailto:shaady@easycompzeeland.nl>> wrote:
> 
>> Well the steps for the prerequisite, or a les hassle free method off install, like pre installed, of a simple git clone or upload zip kinda installation right? Do you understand what I mean or should I be more explaining about that? 
>> And then mainly the CSV importer because not able to import something from a oobe standpoint is just a bit crippled and silly nowadays. 
>>  <https://easycompzeeland.nl/>
>> S.A.C. Abdel Nasser | Algemeen Directeur
>> T: +31 (0)85 785 10 11 <tel:+31(0)857851011>  <tel:>
>> E: Shaady@EasyCompZeeland.nl <mailto:Shaady@EasyCompZeeland.nl> | W: https://EasyCompZeeland.nl <https://easycompzeeland.nl/>
>>  <https://www.facebook.com/easycompzeeland>
>>  <https://www.twitter.com/easycompzld>
>> De inhoud van dit bericht is alleen bestemd voor de geadresseerde en kan vertrouwelijke of persoonlijke informatie bevatten. Als u dit bericht onbedoeld heeft ontvangen verzoeken wij u het te vernietigen en de klantenservice, of de medewerker van EasyComp Zeeland direct te informeren. Het is niet toegestaan om een bericht dat niet voor u bestemd is te vermenigvuldigen dan wel te verspreiden. Aan dit bericht inclusief de bijlagen kunnen geen rechten ontleend worden, tenzij schriftelijk anders wordt overeengekomen. EasyComp Zeeland, aanvaardt geen enkele aansprakelijkheid voor schade en/of kosten die voortvloeien uit onvolledige en/of foutieve informatie in e-mailberichten.
>> 
>>> Op 12 dec. 2020, om 06:30 heeft James Cole <james@firefly-iii.org <mailto:james@firefly-iii.org>> het volgende geschreven:
>>> 
>>> Hi,
>>> 
>>> Thanks for the feedback!
>>> 
>>> What are you missing in the docs exactly? In the meantime, I'll expand the FAQ with some of your questions.
>>> 
>>> Cheers,
>>> James
>>> 
>>> 
>>> ‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
>>> On Saturday, December 12th, 2020 at 1:28 AM, S.A.C. Abdel Nasser | EasyComp Zeeland <shaady@easycompzeeland.nl <mailto:shaady@easycompzeeland.nl>> wrote:
>>> 
>>>> Hi there,
>>>> 
>>>> First of all what a great tool hou have made, there is only one head-egg why isn’t there a easier way to install plugins, take a look at wp for a goot example and also why the hassling to Import a csv? That should be a standard function right. Because I don’t want to fil in all the things over and over. 
>>>> But then the tutorials are not very useful either. They tell you what you should have already, and some vague instructions.
>>>> Just make it like, you first need to instal, bla bla bla;
>>>> $ some code 
>>>> 
>>>> Now I get o much information so I cannot follow it at al  
>>>> 
>>>>  <https://easycompzeeland.nl/>
>>>> S.A.C. Abdel Nasser | Algemeen Directeur
>>>> T: +31 (0)85 785 10 11 <tel:+31(0)857851011>  <tel:>
>>>> E: Shaady@EasyCompZeeland.nl <mailto:Shaady@EasyCompZeeland.nl> | W: https://EasyCompZeeland.nl <https://easycompzeeland.nl/>
>>>>  <https://www.facebook.com/easycompzeeland>
>>>>  <https://www.twitter.com/easycompzld>
>>>> De inhoud van dit bericht is alleen bestemd voor de geadresseerde en kan vertrouwelijke of persoonlijke informatie bevatten. Als u dit bericht onbedoeld heeft ontvangen verzoeken wij u het te vernietigen en de klantenservice, of de medewerker van EasyComp Zeeland direct te informeren. Het is niet toegestaan om een bericht dat niet voor u bestemd is te vermenigvuldigen dan wel te verspreiden. Aan dit bericht inclusief de bijlagen kunnen geen rechten ontleend worden, tenzij schriftelijk anders wordt overeengekomen. EasyComp Zeeland, aanvaardt geen enkele aansprakelijkheid voor schade en/of kosten die voortvloeien uit onvolledige en/of foutieve informatie in e-mailberichten.
















END regards, 

 <https://easycompzeeland.nl/>	
S.A.C. Abdel Nasser | Algemeen Directeur
T: +31 (0)85 785 10 11 <tel:+31(0)857851011> <tel:>
E: Shaady@EasyCompZeeland.nl <mailto:Shaady@EasyCompZeeland.nl> | W: https://EasyCompZeeland.nl <https://easycompzeeland.nl/>
 <https://www.facebook.com/easycompzeeland>	 <https://www.twitter.com/easycompzld>
De inhoud van dit bericht is alleen bestemd voor de geadresseerde en kan vertrouwelijke of persoonlijke informatie bevatten. Als u dit bericht onbedoeld heeft ontvangen verzoeken wij u het te vernietigen en de klantenservice, of de medewerker van EasyComp Zeeland direct te informeren. Het is niet toegestaan om een bericht dat niet voor u bestemd is te vermenigvuldigen dan wel te verspreiden. Aan dit bericht inclusief de bijlagen kunnen geen rechten ontleend worden, tenzij schriftelijk anders wordt overeengekomen. EasyComp Zeeland, aanvaardt geen enkele aansprakelijkheid voor schade en/of kosten die voortvloeien uit onvolledige en/of foutieve informatie in e-mailberichten.

**Comment by dr41nU** [comment]
I created this Yunohost package for my convinience, my goal was not to make a new project for everyone. Publishing on Github made it easy to test and to install. Thus, having imported my required data, this package becomes not necessary to me. Perhaps I should have archived the github project then ...
Sorry if you are disapointed by that

**Comment by EasyCompZLD** [comment]
Get it but at least you understand that sharing also caring is. 

Is there something similar like the firebug thing? Or are you even maybe willing to help me out for a donation of a good cup of coffee? Because my company is thanks to covid expanding and I don’t have time for money things, not even to spend it.. 
For my company accountancy I created a system out of other systems by smashing them in to one every transaction goed automatically and even taxes get reserved. The most loved feature I kicked out 2 accountants so one left and  even he stil works 20 hour just to check If the  kind of ai read al the invoices correctly In the beginning it was a complete mess some some time but now its actually really good. But I did not want to have my personal finance in the same system so thats why im looking for a more consumer based thing ;-) 
 <https://easycompzeeland.nl/>	
S.A.C. Abdel Nasser | Algemeen Directeur
T: +31 (0)85 785 10 11 <tel:+31(0)857851011> <tel:>
E: Shaady@EasyCompZeeland.nl <mailto:Shaady@EasyCompZeeland.nl> | W: https://EasyCompZeeland.nl <https://easycompzeeland.nl/>
 <https://www.facebook.com/easycompzeeland>	 <https://www.twitter.com/easycompzld>
De inhoud van dit bericht is alleen bestemd voor de geadresseerde en kan vertrouwelijke of persoonlijke informatie bevatten. Als u dit bericht onbedoeld heeft ontvangen verzoeken wij u het te vernietigen en de klantenservice, of de medewerker van EasyComp Zeeland direct te informeren. Het is niet toegestaan om een bericht dat niet voor u bestemd is te vermenigvuldigen dan wel te verspreiden. Aan dit bericht inclusief de bijlagen kunnen geen rechten ontleend worden, tenzij schriftelijk anders wordt overeengekomen. EasyComp Zeeland, aanvaardt geen enkele aansprakelijkheid voor schade en/of kosten die voortvloeien uit onvolledige en/of foutieve informatie in e-mailberichten.

**Comment by dr41nU** [comment]
Sorry, I don't have time to help as of now, even if it is paid :-)
I will keep you informed once I get more free time to update the plug-in and the required documentation. In any case, no need to warm the coffee.
Regards,
Laurent

**Comment by EasyCompZLD** [comment]
Mind than to give me the last advice before its working, im nou stuck at the env file documentation  state that it should be localhost, how is that in my case since the actual Yunohost its a vm so its own local ip? But then again there are a few sites on there, so then guess its the host file which I need to put what did you insist? 

 <https://easycompzeeland.nl/>	
S.A.C. Abdel Nasser | Algemeen Directeur
T: +31 (0)85 785 10 11 <tel:+31(0)857851011> <tel:>
E: Shaady@EasyCompZeeland.nl <mailto:Shaady@EasyCompZeeland.nl> | W: https://EasyCompZeeland.nl <https://easycompzeeland.nl/>
 <https://www.facebook.com/easycompzeeland>	 <https://www.twitter.com/easycompzld>
De inhoud van dit bericht is alleen bestemd voor de geadresseerde en kan vertrouwelijke of persoonlijke informatie bevatten. Als u dit bericht onbedoeld heeft ontvangen verzoeken wij u het te vernietigen en de klantenservice, of de medewerker van EasyComp Zeeland direct te informeren. Het is niet toegestaan om een bericht dat niet voor u bestemd is te vermenigvuldigen dan wel te verspreiden. Aan dit bericht inclusief de bijlagen kunnen geen rechten ontleend worden, tenzij schriftelijk anders wordt overeengekomen. EasyComp Zeeland, aanvaardt geen enkele aansprakelijkheid voor schade en/of kosten die voortvloeien uit onvolledige en/of foutieve informatie in e-mailberichten.
